# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./main.go"
bin = "./tmp/main"
include_ext = ["go"] # only watch *.go files
exclude_dir = ["tmp", "vendor", "node_modules", "public"]
delay = 1000

[log]
time = true

[misc]
clean_on_exit = true


